Improve flow typing, and allow Generics, add new items to document
BEWARE: `documentation` is broken because of the `...$Exact<>` type syntax -> disabled for this commit. Must be fixed.

```
{
  "type": "ObjectTypeSpreadProperty",
  "start": 2661,
  "end": 2694,
  "loc": {
    "start": {
      "line": 101,
      "column": 2
    },
    "end": {
      "line": 101,
      "column": 35
    }
  },
  "argument": {
    "type": "GenericTypeAnnotation",
    "start": 2664,
    "end": 2693,
    "loc": {
      "start": {
        "line": 101,
        "column": 5
      },
      "end": {
        "line": 101,
        "column": 34
      }
    },
    "typeParameters": {
      "type": "TypeParameterInstantiation",
      "start": 2670,
      "end": 2693,
      "loc": {
        "start": {
          "line": 101,
          "column": 11
        },
        "end": {
          "line": 101,
          "column": 34
        }
      },
      "params": [
        {
          "type": "GenericTypeAnnotation",
          "start": 2671,
          "end": 2692,
          "loc": {
            "start": {
              "line": 101,
              "column": 12
            },
            "end": {
              "line": 101,
              "column": 33
            }
          },
          "typeParameters": null,
          "id": {
            "type": "Identifier",
            "start": 2671,
            "end": 2692,
            "loc": {
              "start": {
                "line": 101,
                "column": 12
              },
              "end": {
                "line": 101,
                "column": 33
              },
              "identifierName": "HullContextWithClient"
            },
            "name": "HullContextWithClient"
          }
        }
      ]
    },
    "id": {
      "type": "Identifier",
      "start": 2664,
      "end": 2670,
      "loc": {
        "start": {
          "line": 101,
          "column": 5
        },
        "end": {
          "line": 101,
          "column": 11
        },
        "identifierName": "$Exact"
      },
      "name": "$Exact"
    }
  }
}
TypeError: Cannot read property 'name' of undefined
    at [...]/documentation/lib/infer/properties.js:46:62
    at Array.forEach (<anonymous>)
    at inferProperties ([...]/documentation/lib/infer/properties.js:44:24)
    at Array.inferProperties ([...]/documentation/lib/infer/properties.js:61:7)
    at comment ([...]/documentation/lib/index.js:39:25)
    at Array.map (<anonymous>)
    at [...]/documentation/lib/index.js:95:48
    at arrayMap ([...]/documentation/node_modules/lodash/lodash.js:631:23)
    at map ([...]/documentation/node_modules/lodash/lodash.js:9546:14)
    at Function.flatMap ([...]/documentation/node_modules/lodash/lodash.js:9249:26)

```